"""empty message

Revision ID: 04b933a2231e
Revises: 
Create Date: 2020-07-26 16:06:05.145516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b933a2231e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eco_tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('eco_tip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eco_tip',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='eco_tip_pkey')
    )
    op.drop_table('eco_tips')
    # ### end Alembic commands ###
